global:
  storageClass: vault-ebs-sc
  postgresql:
    auth:
      existingSecret: sonarqube-postgres # Name of the secret you created
      secretKeys:
        userPasswordKey: sonarqube-password # Key for the sonarqube user password
        adminPasswordKey: postgres-password # Key for the default 'postgres' user password
      username: sonarqube # The desired default username
      database: sonarqube # The desired default database name