apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-solar-app
  namespace: dev-solar-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-solar-app
  template:
    metadata:
      labels:
        app: dev-solar-app
    spec:
      containers:
<<<<<<< Updated upstream
      - name: solar-app
        image: anas1243/solar-app:dev-c927f17
=======
      - name: dev-solar-app
        image: anas1243/solar-app:main-8f78bc0
>>>>>>> Stashed changes
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "500Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri
              key: MONGO_URI
